version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gateway
    ports:
      - "3307:3306"
volumes:
  redis-data:
  mysql-data: