events {}

http {
  resolver 127.0.0.11;

  upstream gateway_cluster {
    server gateway1:3000;
    server gateway2:3000;
  }

  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/server.cert;
    ssl_certificate_key /etc/nginx/server.key;

    location / {
      proxy_pass http://gateway_cluster;
    }
  }
}